[tool.black]
line-length = 110
target-version = ["py313"]

[tool.isort]
profile = "black"
line_length = 110
known_first_party = ["lsst"]

[tool.lsst_versions]
write_to = "python/lsst/analysis/tools/version.py"

[tool.ruff]
line-length = 110
target-version = "py313"
exclude = [
    "__init__.py",
    "config",  # TODO: remove * imports on DM-54154
    "doc",
]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle
    "F",  # pyflakes
    "W",  # pycodestyle
    "UP",  # pyupgrade
    "I",  # isort
]

[tool.ruff.lint.isort]
known-first-party = ["lsst"]
